package futures

const (
	exchangeName                 = "toobit"
	symbolKey                    = "symbol"
	limitKey                     = "limit"
	orderIDKey                   = "orderId"
	typeKey                      = "type"
	eventKey                     = "event"
	paramsKey                    = "params"
	binaryKey                    = "binary"
	topicKey                     = "topic"
	eventSub                     = "sub"
	eventCancel                  = "cancel"
	topicBookTicker              = "bookTicker"
	topicRealtimes               = "realtimes"
	topicDiffDepth               = "diffDepth"
	topicDepth                   = "depth"
	channelPing                  = "ping"
	channelPersonalPosition      = "personal.position"
	outboundContractPositionInfo = "outboundContractPositionInfo"
	orderTypeLimit               = "LIMIT"
	orderTypeMarket              = "MARKET"
	tifGTC                       = "GTC"
	posSideLong                  = "LONG"
	posSideShort                 = "SHORT"
	posSideBoth                  = "BOTH"
	sideBuy                      = "BUY"
	sideSell                     = "SELL"
)
