apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-bot
  namespace: default
  labels:
    app: crypto-bot
spec:
  replicas: 1
  strategy:
    type: Recreate # Ensures only 1 pod is running at a time (preventing double order placement)
  selector:
    matchLabels:
      app: crypto-bot
  template:
    metadata:
      labels:
        app: crypto-bot
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3100"
    spec:
      securityContext:
        fsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
      containers:
        - name: bot
          image: crypto-bot:latest
          imagePullPolicy: Never # Instructs local cluster (K3d/Minikube) to use local image
          args:
            - "-sys"
            - "/app/configs/funding/prod/system.jsonc"
            - "-exch"
            - "/app/configs/funding/prod/exchange.jsonc"
            - "-bot"
            - "/app/configs/funding/prod/funding.jsonc"
            - "-blacklist"
            - "/app/configs/funding/prod/blacklist.jsonc"
            - "-reversion"
            - "/app/configs/funding/prod/reversion.jsonc"
            - "-obfuscator"
            - "/app/configs/funding/prod/obfuscator.jsonc"
            - "-dilution"
            - "/app/configs/funding/prod/dilution.jsonc"
          envFrom:
            - secretRef:
                name: crypto-bot-vault-secrets
          resources:
            limits:
              cpu: "4000m"
              memory: "2Gi"
            requests:
              cpu: "4000m"
              memory: "500Mb"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: configs
              mountPath: /app/configs/funding/prod
              readOnly: true
      volumes:
        - name: configs
          configMap:
            name: crypto-bot-configs
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-bot
  namespace: default
spec:
  selector:
    app: crypto-bot
  ports:
    - port: 3100
      targetPort: 3100
  type: ClusterIP
