apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-bot
  namespace: default
  labels:
    app: crypto-bot
    bot_type: funding
spec:
  replicas: 1
  strategy:
    type: Recreate # Ensures only 1 pod is running at a time (preventing double order placement)
  selector:
    matchLabels:
      app: crypto-bot
  template:
    metadata:
      labels:
        app: crypto-bot
        bot_type: funding
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3100"
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      securityContext:
        fsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
      containers:
        - name: bot
          image: crypto-bot:latest
          imagePullPolicy: Never # Instructs local cluster (K3d/Minikube) to use local image
          args:
            - "-accounts"
            - "/app/configs/accounts.jsonc"
            - "-sys"
            - "/app/configs/system.jsonc"
            - "-exch"
            - "/app/configs/exchange.jsonc"
            - "-blacklist"
            - "/app/configs/blacklist.jsonc"
            - "-reversion"
            - "/app/configs/reversion.jsonc"
          env:
            - name: GOGC
              value: "200"
            - name: GOMEMLIMIT
              value: "800MiB"
          envFrom:
            - secretRef:
                name: crypto-bot-vault-secrets
          resources:
            limits:
              cpu: "4"
              memory: "1Gi"
            requests:
              cpu: "4"
              memory: "1Gi"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: configs
              mountPath: /app/configs
              readOnly: true
      volumes:
        - name: configs
          configMap:
            name: funding-configs
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-bot
  namespace: default
spec:
  selector:
    app: crypto-bot
  ports:
    - port: 3100
      targetPort: 3100
  type: ClusterIP
