server:
  retention: 30d
  persistentVolume:
    enabled: true
    size: 8Gi
    storageClass: "local-path"
  service:
    type: ClusterIP
    servicePort: 80

alertmanager:
  enabled: false

pushgateway:
  enabled: false

prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
