apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: crypto-bot-auth
  namespace: default
spec:
  vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: crypto-bot-role
    serviceAccount: crypto-bot
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: crypto-bot-vault-secrets
  namespace: default
spec:
  vaultAuthRef: crypto-bot-auth
  mount: secret
  type: kv-v2
  path: crypto-bot
  destination:
    name: crypto-bot-vault-secrets
    type: Opaque
    create: true
