package hotcoin

const (
	exchangeName     = "hotcoin"
	sideOpenLong     = "open_long"
	sideCloseShort   = "close_short"
	sideOpenShort    = "open_short"
	sideCloseLong    = "close_long"
	pageSizeKey      = "pageSize"
	typeKey          = "type"
	sideKey          = "side"
	amountKey        = "amount"
	contractCodeKey  = "contractCode"
	wsChannelTicker  = "market.ticker"
	keySubscribed    = "subscribed"
	subAction        = "sub"
	unsubAction      = "unsub"
	eventKey         = "event"
	paramsKey        = "params"
	bizKey           = "biz"
	perpetualBiz     = "perpetual"
	positionsType    = "position"
	positionsPlural  = "positions"
	fillsType        = "fills"
	pingValue        = "ping"
	zipParam         = "zip"
	orderIDKey       = "orderId"
	symbolKey        = "symbol"
	signinEvent      = "signin"
	personalPosition = "personal.position"
	personalOrder    = "personal.order"
	subscribeEvent   = "subscribe"
	unsubscribeEvent = "unsubscribe"
	tickerType       = "ticker"
	depthType        = "depth"
	serializeKey     = "serialize"
	sideLong         = "long"
	sideShort        = "short"
	startDateKey     = "startDate"
)
