// Code generated by MockGen. DO NOT EDIT.
// Source: crypto-bot/internal/infrastructure/watcher (interfaces: OrderNotifier)
//
// Generated by this command:
//
//	mockgen -destination mock_watcher.go -package mocks -typed crypto-bot/internal/infrastructure/watcher OrderNotifier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	exchange "crypto-bot/internal/infrastructure/exchange"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderNotifier is a mock of OrderNotifier interface.
type MockOrderNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockOrderNotifierMockRecorder
	isgomock struct{}
}

// MockOrderNotifierMockRecorder is the mock recorder for MockOrderNotifier.
type MockOrderNotifierMockRecorder struct {
	mock *MockOrderNotifier
}

// NewMockOrderNotifier creates a new mock instance.
func NewMockOrderNotifier(ctrl *gomock.Controller) *MockOrderNotifier {
	mock := &MockOrderNotifier{ctrl: ctrl}
	mock.recorder = &MockOrderNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderNotifier) EXPECT() *MockOrderNotifierMockRecorder {
	return m.recorder
}

// OnOrderUpdate mocks base method.
func (m *MockOrderNotifier) OnOrderUpdate(orderID string, timeout time.Duration, callback func(exchange.WsOrderDeal)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnOrderUpdate", orderID, timeout, callback)
}

// OnOrderUpdate indicates an expected call of OnOrderUpdate.
func (mr *MockOrderNotifierMockRecorder) OnOrderUpdate(orderID, timeout, callback any) *MockOrderNotifierOnOrderUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnOrderUpdate", reflect.TypeOf((*MockOrderNotifier)(nil).OnOrderUpdate), orderID, timeout, callback)
	return &MockOrderNotifierOnOrderUpdateCall{Call: call}
}

// MockOrderNotifierOnOrderUpdateCall wrap *gomock.Call
type MockOrderNotifierOnOrderUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderNotifierOnOrderUpdateCall) Return() *MockOrderNotifierOnOrderUpdateCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderNotifierOnOrderUpdateCall) Do(f func(string, time.Duration, func(exchange.WsOrderDeal))) *MockOrderNotifierOnOrderUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderNotifierOnOrderUpdateCall) DoAndReturn(f func(string, time.Duration, func(exchange.WsOrderDeal))) *MockOrderNotifierOnOrderUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveOrderCallback mocks base method.
func (m *MockOrderNotifier) RemoveOrderCallback(orderID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveOrderCallback", orderID)
}

// RemoveOrderCallback indicates an expected call of RemoveOrderCallback.
func (mr *MockOrderNotifierMockRecorder) RemoveOrderCallback(orderID any) *MockOrderNotifierRemoveOrderCallbackCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOrderCallback", reflect.TypeOf((*MockOrderNotifier)(nil).RemoveOrderCallback), orderID)
	return &MockOrderNotifierRemoveOrderCallbackCall{Call: call}
}

// MockOrderNotifierRemoveOrderCallbackCall wrap *gomock.Call
type MockOrderNotifierRemoveOrderCallbackCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderNotifierRemoveOrderCallbackCall) Return() *MockOrderNotifierRemoveOrderCallbackCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderNotifierRemoveOrderCallbackCall) Do(f func(string)) *MockOrderNotifierRemoveOrderCallbackCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderNotifierRemoveOrderCallbackCall) DoAndReturn(f func(string)) *MockOrderNotifierRemoveOrderCallbackCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
