// Code generated by MockGen. DO NOT EDIT.
// Source: crypto-bot/internal/infrastructure/exchange (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination mock_exchange.go -package mocks -typed crypto-bot/internal/infrastructure/exchange Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "crypto-bot/internal/domain"
	exchange "crypto-bot/internal/infrastructure/exchange"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CancelAllOpenOrders mocks base method.
func (m *MockClient) CancelAllOpenOrders(ctx context.Context, symbol string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelAllOpenOrders", ctx, symbol)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelAllOpenOrders indicates an expected call of CancelAllOpenOrders.
func (mr *MockClientMockRecorder) CancelAllOpenOrders(ctx, symbol any) *MockClientCancelAllOpenOrdersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAllOpenOrders", reflect.TypeOf((*MockClient)(nil).CancelAllOpenOrders), ctx, symbol)
	return &MockClientCancelAllOpenOrdersCall{Call: call}
}

// MockClientCancelAllOpenOrdersCall wrap *gomock.Call
type MockClientCancelAllOpenOrdersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCancelAllOpenOrdersCall) Return(arg0 error) *MockClientCancelAllOpenOrdersCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCancelAllOpenOrdersCall) Do(f func(context.Context, string) error) *MockClientCancelAllOpenOrdersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCancelAllOpenOrdersCall) DoAndReturn(f func(context.Context, string) error) *MockClientCancelAllOpenOrdersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CancelOrder mocks base method.
func (m *MockClient) CancelOrder(ctx context.Context, symbol, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", ctx, symbol, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockClientMockRecorder) CancelOrder(ctx, symbol, orderID any) *MockClientCancelOrderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockClient)(nil).CancelOrder), ctx, symbol, orderID)
	return &MockClientCancelOrderCall{Call: call}
}

// MockClientCancelOrderCall wrap *gomock.Call
type MockClientCancelOrderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCancelOrderCall) Return(arg0 error) *MockClientCancelOrderCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCancelOrderCall) Do(f func(context.Context, string, string) error) *MockClientCancelOrderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCancelOrderCall) DoAndReturn(f func(context.Context, string, string) error) *MockClientCancelOrderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CancelOrders mocks base method.
func (m *MockClient) CancelOrders(ctx context.Context, orderIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrders", ctx, orderIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelOrders indicates an expected call of CancelOrders.
func (mr *MockClientMockRecorder) CancelOrders(ctx, orderIDs any) *MockClientCancelOrdersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrders", reflect.TypeOf((*MockClient)(nil).CancelOrders), ctx, orderIDs)
	return &MockClientCancelOrdersCall{Call: call}
}

// MockClientCancelOrdersCall wrap *gomock.Call
type MockClientCancelOrdersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCancelOrdersCall) Return(arg0 error) *MockClientCancelOrdersCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCancelOrdersCall) Do(f func(context.Context, []string) error) *MockClientCancelOrdersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCancelOrdersCall) DoAndReturn(f func(context.Context, []string) error) *MockClientCancelOrdersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ChangeLeverage mocks base method.
func (m *MockClient) ChangeLeverage(ctx context.Context, req exchange.ChangeLeverageRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeLeverage", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeLeverage indicates an expected call of ChangeLeverage.
func (mr *MockClientMockRecorder) ChangeLeverage(ctx, req any) *MockClientChangeLeverageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeLeverage", reflect.TypeOf((*MockClient)(nil).ChangeLeverage), ctx, req)
	return &MockClientChangeLeverageCall{Call: call}
}

// MockClientChangeLeverageCall wrap *gomock.Call
type MockClientChangeLeverageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientChangeLeverageCall) Return(arg0 error) *MockClientChangeLeverageCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientChangeLeverageCall) Do(f func(context.Context, exchange.ChangeLeverageRequest) error) *MockClientChangeLeverageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientChangeLeverageCall) DoAndReturn(f func(context.Context, exchange.ChangeLeverageRequest) error) *MockClientChangeLeverageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CloseAllPositions mocks base method.
func (m *MockClient) CloseAllPositions(ctx context.Context, symbol string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAllPositions", ctx, symbol)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseAllPositions indicates an expected call of CloseAllPositions.
func (mr *MockClientMockRecorder) CloseAllPositions(ctx, symbol any) *MockClientCloseAllPositionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAllPositions", reflect.TypeOf((*MockClient)(nil).CloseAllPositions), ctx, symbol)
	return &MockClientCloseAllPositionsCall{Call: call}
}

// MockClientCloseAllPositionsCall wrap *gomock.Call
type MockClientCloseAllPositionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCloseAllPositionsCall) Return(arg0 error) *MockClientCloseAllPositionsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCloseAllPositionsCall) Do(f func(context.Context, string) error) *MockClientCloseAllPositionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCloseAllPositionsCall) DoAndReturn(f func(context.Context, string) error) *MockClientCloseAllPositionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ClosePosition mocks base method.
func (m *MockClient) ClosePosition(ctx context.Context, symbol string, closeSide domain.Side, volume float64, positionMode domain.PositionMode, leverage int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClosePosition", ctx, symbol, closeSide, volume, positionMode, leverage)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClosePosition indicates an expected call of ClosePosition.
func (mr *MockClientMockRecorder) ClosePosition(ctx, symbol, closeSide, volume, positionMode, leverage any) *MockClientClosePositionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClosePosition", reflect.TypeOf((*MockClient)(nil).ClosePosition), ctx, symbol, closeSide, volume, positionMode, leverage)
	return &MockClientClosePositionCall{Call: call}
}

// MockClientClosePositionCall wrap *gomock.Call
type MockClientClosePositionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientClosePositionCall) Return(arg0 error) *MockClientClosePositionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientClosePositionCall) Do(f func(context.Context, string, domain.Side, float64, domain.PositionMode, int) error) *MockClientClosePositionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientClosePositionCall) DoAndReturn(f func(context.Context, string, domain.Side, float64, domain.PositionMode, int) error) *MockClientClosePositionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateOrder mocks base method.
func (m *MockClient) CreateOrder(ctx context.Context, req exchange.SubmitOrderRequest) (exchange.CreateOrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, req)
	ret0, _ := ret[0].(exchange.CreateOrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockClientMockRecorder) CreateOrder(ctx, req any) *MockClientCreateOrderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockClient)(nil).CreateOrder), ctx, req)
	return &MockClientCreateOrderCall{Call: call}
}

// MockClientCreateOrderCall wrap *gomock.Call
type MockClientCreateOrderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCreateOrderCall) Return(arg0 exchange.CreateOrderResult, arg1 error) *MockClientCreateOrderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCreateOrderCall) Do(f func(context.Context, exchange.SubmitOrderRequest) (exchange.CreateOrderResult, error)) *MockClientCreateOrderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCreateOrderCall) DoAndReturn(f func(context.Context, exchange.SubmitOrderRequest) (exchange.CreateOrderResult, error)) *MockClientCreateOrderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetContractDetails mocks base method.
func (m *MockClient) GetContractDetails(ctx context.Context) ([]exchange.ContractDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContractDetails", ctx)
	ret0, _ := ret[0].([]exchange.ContractDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContractDetails indicates an expected call of GetContractDetails.
func (mr *MockClientMockRecorder) GetContractDetails(ctx any) *MockClientGetContractDetailsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContractDetails", reflect.TypeOf((*MockClient)(nil).GetContractDetails), ctx)
	return &MockClientGetContractDetailsCall{Call: call}
}

// MockClientGetContractDetailsCall wrap *gomock.Call
type MockClientGetContractDetailsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetContractDetailsCall) Return(arg0 []exchange.ContractDetail, arg1 error) *MockClientGetContractDetailsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetContractDetailsCall) Do(f func(context.Context) ([]exchange.ContractDetail, error)) *MockClientGetContractDetailsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetContractDetailsCall) DoAndReturn(f func(context.Context) ([]exchange.ContractDetail, error)) *MockClientGetContractDetailsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetFundingRates mocks base method.
func (m *MockClient) GetFundingRates(ctx context.Context, symbols []string) ([]exchange.FundingRateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFundingRates", ctx, symbols)
	ret0, _ := ret[0].([]exchange.FundingRateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFundingRates indicates an expected call of GetFundingRates.
func (mr *MockClientMockRecorder) GetFundingRates(ctx, symbols any) *MockClientGetFundingRatesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFundingRates", reflect.TypeOf((*MockClient)(nil).GetFundingRates), ctx, symbols)
	return &MockClientGetFundingRatesCall{Call: call}
}

// MockClientGetFundingRatesCall wrap *gomock.Call
type MockClientGetFundingRatesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetFundingRatesCall) Return(arg0 []exchange.FundingRateResult, arg1 error) *MockClientGetFundingRatesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetFundingRatesCall) Do(f func(context.Context, []string) ([]exchange.FundingRateResult, error)) *MockClientGetFundingRatesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetFundingRatesCall) DoAndReturn(f func(context.Context, []string) ([]exchange.FundingRateResult, error)) *MockClientGetFundingRatesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOpenOrders mocks base method.
func (m *MockClient) GetOpenOrders(ctx context.Context, symbol string) ([]exchange.OrderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenOrders", ctx, symbol)
	ret0, _ := ret[0].([]exchange.OrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenOrders indicates an expected call of GetOpenOrders.
func (mr *MockClientMockRecorder) GetOpenOrders(ctx, symbol any) *MockClientGetOpenOrdersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenOrders", reflect.TypeOf((*MockClient)(nil).GetOpenOrders), ctx, symbol)
	return &MockClientGetOpenOrdersCall{Call: call}
}

// MockClientGetOpenOrdersCall wrap *gomock.Call
type MockClientGetOpenOrdersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetOpenOrdersCall) Return(arg0 []exchange.OrderInfo, arg1 error) *MockClientGetOpenOrdersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetOpenOrdersCall) Do(f func(context.Context, string) ([]exchange.OrderInfo, error)) *MockClientGetOpenOrdersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetOpenOrdersCall) DoAndReturn(f func(context.Context, string) ([]exchange.OrderInfo, error)) *MockClientGetOpenOrdersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOpenPositions mocks base method.
func (m *MockClient) GetOpenPositions(ctx context.Context, symbol string) ([]exchange.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenPositions", ctx, symbol)
	ret0, _ := ret[0].([]exchange.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenPositions indicates an expected call of GetOpenPositions.
func (mr *MockClientMockRecorder) GetOpenPositions(ctx, symbol any) *MockClientGetOpenPositionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenPositions", reflect.TypeOf((*MockClient)(nil).GetOpenPositions), ctx, symbol)
	return &MockClientGetOpenPositionsCall{Call: call}
}

// MockClientGetOpenPositionsCall wrap *gomock.Call
type MockClientGetOpenPositionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetOpenPositionsCall) Return(arg0 []exchange.Position, arg1 error) *MockClientGetOpenPositionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetOpenPositionsCall) Do(f func(context.Context, string) ([]exchange.Position, error)) *MockClientGetOpenPositionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetOpenPositionsCall) DoAndReturn(f func(context.Context, string) ([]exchange.Position, error)) *MockClientGetOpenPositionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOrder mocks base method.
func (m *MockClient) GetOrder(ctx context.Context, symbol, orderID string) (*exchange.OrderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, symbol, orderID)
	ret0, _ := ret[0].(*exchange.OrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockClientMockRecorder) GetOrder(ctx, symbol, orderID any) *MockClientGetOrderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockClient)(nil).GetOrder), ctx, symbol, orderID)
	return &MockClientGetOrderCall{Call: call}
}

// MockClientGetOrderCall wrap *gomock.Call
type MockClientGetOrderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetOrderCall) Return(arg0 *exchange.OrderInfo, arg1 error) *MockClientGetOrderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetOrderCall) Do(f func(context.Context, string, string) (*exchange.OrderInfo, error)) *MockClientGetOrderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetOrderCall) DoAndReturn(f func(context.Context, string, string) (*exchange.OrderInfo, error)) *MockClientGetOrderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOrderByExternalID mocks base method.
func (m *MockClient) GetOrderByExternalID(ctx context.Context, symbol, externalOrderID string) (*exchange.OrderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByExternalID", ctx, symbol, externalOrderID)
	ret0, _ := ret[0].(*exchange.OrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByExternalID indicates an expected call of GetOrderByExternalID.
func (mr *MockClientMockRecorder) GetOrderByExternalID(ctx, symbol, externalOrderID any) *MockClientGetOrderByExternalIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByExternalID", reflect.TypeOf((*MockClient)(nil).GetOrderByExternalID), ctx, symbol, externalOrderID)
	return &MockClientGetOrderByExternalIDCall{Call: call}
}

// MockClientGetOrderByExternalIDCall wrap *gomock.Call
type MockClientGetOrderByExternalIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetOrderByExternalIDCall) Return(arg0 *exchange.OrderInfo, arg1 error) *MockClientGetOrderByExternalIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetOrderByExternalIDCall) Do(f func(context.Context, string, string) (*exchange.OrderInfo, error)) *MockClientGetOrderByExternalIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetOrderByExternalIDCall) DoAndReturn(f func(context.Context, string, string) (*exchange.OrderInfo, error)) *MockClientGetOrderByExternalIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPotentialFundingSymbols mocks base method.
func (m *MockClient) GetPotentialFundingSymbols(ctx context.Context, minVol24h, maxVol24h float64, whitelist, blacklist []string) ([]exchange.PotentialFundingResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPotentialFundingSymbols", ctx, minVol24h, maxVol24h, whitelist, blacklist)
	ret0, _ := ret[0].([]exchange.PotentialFundingResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPotentialFundingSymbols indicates an expected call of GetPotentialFundingSymbols.
func (mr *MockClientMockRecorder) GetPotentialFundingSymbols(ctx, minVol24h, maxVol24h, whitelist, blacklist any) *MockClientGetPotentialFundingSymbolsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPotentialFundingSymbols", reflect.TypeOf((*MockClient)(nil).GetPotentialFundingSymbols), ctx, minVol24h, maxVol24h, whitelist, blacklist)
	return &MockClientGetPotentialFundingSymbolsCall{Call: call}
}

// MockClientGetPotentialFundingSymbolsCall wrap *gomock.Call
type MockClientGetPotentialFundingSymbolsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetPotentialFundingSymbolsCall) Return(arg0 []exchange.PotentialFundingResult, arg1 error) *MockClientGetPotentialFundingSymbolsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetPotentialFundingSymbolsCall) Do(f func(context.Context, float64, float64, []string, []string) ([]exchange.PotentialFundingResult, error)) *MockClientGetPotentialFundingSymbolsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetPotentialFundingSymbolsCall) DoAndReturn(f func(context.Context, float64, float64, []string, []string) ([]exchange.PotentialFundingResult, error)) *MockClientGetPotentialFundingSymbolsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetServerTime mocks base method.
func (m *MockClient) GetServerTime(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerTime", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerTime indicates an expected call of GetServerTime.
func (mr *MockClientMockRecorder) GetServerTime(ctx any) *MockClientGetServerTimeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerTime", reflect.TypeOf((*MockClient)(nil).GetServerTime), ctx)
	return &MockClientGetServerTimeCall{Call: call}
}

// MockClientGetServerTimeCall wrap *gomock.Call
type MockClientGetServerTimeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetServerTimeCall) Return(arg0 int64, arg1 error) *MockClientGetServerTimeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetServerTimeCall) Do(f func(context.Context) (int64, error)) *MockClientGetServerTimeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetServerTimeCall) DoAndReturn(f func(context.Context) (int64, error)) *MockClientGetServerTimeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTickers mocks base method.
func (m *MockClient) GetTickers(ctx context.Context, symbol string) ([]exchange.Ticker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTickers", ctx, symbol)
	ret0, _ := ret[0].([]exchange.Ticker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTickers indicates an expected call of GetTickers.
func (mr *MockClientMockRecorder) GetTickers(ctx, symbol any) *MockClientGetTickersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTickers", reflect.TypeOf((*MockClient)(nil).GetTickers), ctx, symbol)
	return &MockClientGetTickersCall{Call: call}
}

// MockClientGetTickersCall wrap *gomock.Call
type MockClientGetTickersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetTickersCall) Return(arg0 []exchange.Ticker, arg1 error) *MockClientGetTickersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetTickersCall) Do(f func(context.Context, string) ([]exchange.Ticker, error)) *MockClientGetTickersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetTickersCall) DoAndReturn(f func(context.Context, string) ([]exchange.Ticker, error)) *MockClientGetTickersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SupportLeverageOnOrder mocks base method.
func (m *MockClient) SupportLeverageOnOrder() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportLeverageOnOrder")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportLeverageOnOrder indicates an expected call of SupportLeverageOnOrder.
func (mr *MockClientMockRecorder) SupportLeverageOnOrder() *MockClientSupportLeverageOnOrderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportLeverageOnOrder", reflect.TypeOf((*MockClient)(nil).SupportLeverageOnOrder))
	return &MockClientSupportLeverageOnOrderCall{Call: call}
}

// MockClientSupportLeverageOnOrderCall wrap *gomock.Call
type MockClientSupportLeverageOnOrderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientSupportLeverageOnOrderCall) Return(arg0 bool) *MockClientSupportLeverageOnOrderCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientSupportLeverageOnOrderCall) Do(f func() bool) *MockClientSupportLeverageOnOrderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientSupportLeverageOnOrderCall) DoAndReturn(f func() bool) *MockClientSupportLeverageOnOrderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SwitchMarginMode mocks base method.
func (m *MockClient) SwitchMarginMode(ctx context.Context, symbol, marginMode string, leverage int, side domain.Side) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchMarginMode", ctx, symbol, marginMode, leverage, side)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwitchMarginMode indicates an expected call of SwitchMarginMode.
func (mr *MockClientMockRecorder) SwitchMarginMode(ctx, symbol, marginMode, leverage, side any) *MockClientSwitchMarginModeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchMarginMode", reflect.TypeOf((*MockClient)(nil).SwitchMarginMode), ctx, symbol, marginMode, leverage, side)
	return &MockClientSwitchMarginModeCall{Call: call}
}

// MockClientSwitchMarginModeCall wrap *gomock.Call
type MockClientSwitchMarginModeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientSwitchMarginModeCall) Return(arg0 error) *MockClientSwitchMarginModeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientSwitchMarginModeCall) Do(f func(context.Context, string, string, int, domain.Side) error) *MockClientSwitchMarginModeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientSwitchMarginModeCall) DoAndReturn(f func(context.Context, string, string, int, domain.Side) error) *MockClientSwitchMarginModeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WarmUp mocks base method.
func (m *MockClient) WarmUp(ctx context.Context, interval time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WarmUp", ctx, interval)
}

// WarmUp indicates an expected call of WarmUp.
func (mr *MockClientMockRecorder) WarmUp(ctx, interval any) *MockClientWarmUpCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarmUp", reflect.TypeOf((*MockClient)(nil).WarmUp), ctx, interval)
	return &MockClientWarmUpCall{Call: call}
}

// MockClientWarmUpCall wrap *gomock.Call
type MockClientWarmUpCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientWarmUpCall) Return() *MockClientWarmUpCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientWarmUpCall) Do(f func(context.Context, time.Duration)) *MockClientWarmUpCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientWarmUpCall) DoAndReturn(f func(context.Context, time.Duration)) *MockClientWarmUpCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
