// Code generated by MockGen. DO NOT EDIT.
// Source: crypto-bot/internal/infrastructure/store (interfaces: TickerReader,ContractReader,PriceReader,FundingReader,DepthReader,KlineReadWriter)
//
// Generated by this command:
//
//	mockgen -destination mock_store.go -package mocks -typed crypto-bot/internal/infrastructure/store TickerReader,ContractReader,PriceReader,FundingReader,DepthReader,KlineReadWriter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "crypto-bot/internal/domain"
	store "crypto-bot/internal/infrastructure/store"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTickerReader is a mock of TickerReader interface.
type MockTickerReader struct {
	ctrl     *gomock.Controller
	recorder *MockTickerReaderMockRecorder
	isgomock struct{}
}

// MockTickerReaderMockRecorder is the mock recorder for MockTickerReader.
type MockTickerReaderMockRecorder struct {
	mock *MockTickerReader
}

// NewMockTickerReader creates a new mock instance.
func NewMockTickerReader(ctrl *gomock.Controller) *MockTickerReader {
	mock := &MockTickerReader{ctrl: ctrl}
	mock.recorder = &MockTickerReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTickerReader) EXPECT() *MockTickerReaderMockRecorder {
	return m.recorder
}

// GetAllTickers mocks base method.
func (m *MockTickerReader) GetAllTickers(ctx context.Context) []*store.TickerData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTickers", ctx)
	ret0, _ := ret[0].([]*store.TickerData)
	return ret0
}

// GetAllTickers indicates an expected call of GetAllTickers.
func (mr *MockTickerReaderMockRecorder) GetAllTickers(ctx any) *MockTickerReaderGetAllTickersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTickers", reflect.TypeOf((*MockTickerReader)(nil).GetAllTickers), ctx)
	return &MockTickerReaderGetAllTickersCall{Call: call}
}

// MockTickerReaderGetAllTickersCall wrap *gomock.Call
type MockTickerReaderGetAllTickersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTickerReaderGetAllTickersCall) Return(arg0 []*store.TickerData) *MockTickerReaderGetAllTickersCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTickerReaderGetAllTickersCall) Do(f func(context.Context) []*store.TickerData) *MockTickerReaderGetAllTickersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTickerReaderGetAllTickersCall) DoAndReturn(f func(context.Context) []*store.TickerData) *MockTickerReaderGetAllTickersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTicker mocks base method.
func (m *MockTickerReader) GetTicker(ctx context.Context, symbol string) (*store.TickerData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicker", ctx, symbol)
	ret0, _ := ret[0].(*store.TickerData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicker indicates an expected call of GetTicker.
func (mr *MockTickerReaderMockRecorder) GetTicker(ctx, symbol any) *MockTickerReaderGetTickerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicker", reflect.TypeOf((*MockTickerReader)(nil).GetTicker), ctx, symbol)
	return &MockTickerReaderGetTickerCall{Call: call}
}

// MockTickerReaderGetTickerCall wrap *gomock.Call
type MockTickerReaderGetTickerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTickerReaderGetTickerCall) Return(arg0 *store.TickerData, arg1 error) *MockTickerReaderGetTickerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTickerReaderGetTickerCall) Do(f func(context.Context, string) (*store.TickerData, error)) *MockTickerReaderGetTickerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTickerReaderGetTickerCall) DoAndReturn(f func(context.Context, string) (*store.TickerData, error)) *MockTickerReaderGetTickerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockContractReader is a mock of ContractReader interface.
type MockContractReader struct {
	ctrl     *gomock.Controller
	recorder *MockContractReaderMockRecorder
	isgomock struct{}
}

// MockContractReaderMockRecorder is the mock recorder for MockContractReader.
type MockContractReaderMockRecorder struct {
	mock *MockContractReader
}

// NewMockContractReader creates a new mock instance.
func NewMockContractReader(ctrl *gomock.Controller) *MockContractReader {
	mock := &MockContractReader{ctrl: ctrl}
	mock.recorder = &MockContractReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractReader) EXPECT() *MockContractReaderMockRecorder {
	return m.recorder
}

// GetContract mocks base method.
func (m *MockContractReader) GetContract(ctx context.Context, symbol string) (*store.ContractData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContract", ctx, symbol)
	ret0, _ := ret[0].(*store.ContractData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContract indicates an expected call of GetContract.
func (mr *MockContractReaderMockRecorder) GetContract(ctx, symbol any) *MockContractReaderGetContractCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContract", reflect.TypeOf((*MockContractReader)(nil).GetContract), ctx, symbol)
	return &MockContractReaderGetContractCall{Call: call}
}

// MockContractReaderGetContractCall wrap *gomock.Call
type MockContractReaderGetContractCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContractReaderGetContractCall) Return(arg0 *store.ContractData, arg1 error) *MockContractReaderGetContractCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContractReaderGetContractCall) Do(f func(context.Context, string) (*store.ContractData, error)) *MockContractReaderGetContractCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContractReaderGetContractCall) DoAndReturn(f func(context.Context, string) (*store.ContractData, error)) *MockContractReaderGetContractCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockPriceReader is a mock of PriceReader interface.
type MockPriceReader struct {
	ctrl     *gomock.Controller
	recorder *MockPriceReaderMockRecorder
	isgomock struct{}
}

// MockPriceReaderMockRecorder is the mock recorder for MockPriceReader.
type MockPriceReaderMockRecorder struct {
	mock *MockPriceReader
}

// NewMockPriceReader creates a new mock instance.
func NewMockPriceReader(ctrl *gomock.Controller) *MockPriceReader {
	mock := &MockPriceReader{ctrl: ctrl}
	mock.recorder = &MockPriceReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceReader) EXPECT() *MockPriceReaderMockRecorder {
	return m.recorder
}

// GetBestBidAsk mocks base method.
func (m *MockPriceReader) GetBestBidAsk(ctx context.Context, symbol string) (float64, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBestBidAsk", ctx, symbol)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBestBidAsk indicates an expected call of GetBestBidAsk.
func (mr *MockPriceReaderMockRecorder) GetBestBidAsk(ctx, symbol any) *MockPriceReaderGetBestBidAskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBestBidAsk", reflect.TypeOf((*MockPriceReader)(nil).GetBestBidAsk), ctx, symbol)
	return &MockPriceReaderGetBestBidAskCall{Call: call}
}

// MockPriceReaderGetBestBidAskCall wrap *gomock.Call
type MockPriceReaderGetBestBidAskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPriceReaderGetBestBidAskCall) Return(bid, ask float64, err error) *MockPriceReaderGetBestBidAskCall {
	c.Call = c.Call.Return(bid, ask, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPriceReaderGetBestBidAskCall) Do(f func(context.Context, string) (float64, float64, error)) *MockPriceReaderGetBestBidAskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPriceReaderGetBestBidAskCall) DoAndReturn(f func(context.Context, string) (float64, float64, error)) *MockPriceReaderGetBestBidAskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPrice mocks base method.
func (m *MockPriceReader) GetPrice(ctx context.Context, symbol string, maxAge time.Duration) (*store.PriceData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrice", ctx, symbol, maxAge)
	ret0, _ := ret[0].(*store.PriceData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrice indicates an expected call of GetPrice.
func (mr *MockPriceReaderMockRecorder) GetPrice(ctx, symbol, maxAge any) *MockPriceReaderGetPriceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrice", reflect.TypeOf((*MockPriceReader)(nil).GetPrice), ctx, symbol, maxAge)
	return &MockPriceReaderGetPriceCall{Call: call}
}

// MockPriceReaderGetPriceCall wrap *gomock.Call
type MockPriceReaderGetPriceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPriceReaderGetPriceCall) Return(arg0 *store.PriceData, arg1 error) *MockPriceReaderGetPriceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPriceReaderGetPriceCall) Do(f func(context.Context, string, time.Duration) (*store.PriceData, error)) *MockPriceReaderGetPriceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPriceReaderGetPriceCall) DoAndReturn(f func(context.Context, string, time.Duration) (*store.PriceData, error)) *MockPriceReaderGetPriceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubscribePrice mocks base method.
func (m *MockPriceReader) SubscribePrice(ctx context.Context, symbol string) <-chan *store.PriceData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribePrice", ctx, symbol)
	ret0, _ := ret[0].(<-chan *store.PriceData)
	return ret0
}

// SubscribePrice indicates an expected call of SubscribePrice.
func (mr *MockPriceReaderMockRecorder) SubscribePrice(ctx, symbol any) *MockPriceReaderSubscribePriceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribePrice", reflect.TypeOf((*MockPriceReader)(nil).SubscribePrice), ctx, symbol)
	return &MockPriceReaderSubscribePriceCall{Call: call}
}

// MockPriceReaderSubscribePriceCall wrap *gomock.Call
type MockPriceReaderSubscribePriceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPriceReaderSubscribePriceCall) Return(ch <-chan *store.PriceData) *MockPriceReaderSubscribePriceCall {
	c.Call = c.Call.Return(ch)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPriceReaderSubscribePriceCall) Do(f func(context.Context, string) <-chan *store.PriceData) *MockPriceReaderSubscribePriceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPriceReaderSubscribePriceCall) DoAndReturn(f func(context.Context, string) <-chan *store.PriceData) *MockPriceReaderSubscribePriceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PriceAge mocks base method.
func (m *MockPriceReader) PriceAge(symbol string) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PriceAge", symbol)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// PriceAge indicates an expected call of PriceAge.
func (mr *MockPriceReaderMockRecorder) PriceAge(symbol any) *MockPriceReaderPriceAgeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PriceAge", reflect.TypeOf((*MockPriceReader)(nil).PriceAge), symbol)
	return &MockPriceReaderPriceAgeCall{Call: call}
}

// MockPriceReaderPriceAgeCall wrap *gomock.Call
type MockPriceReaderPriceAgeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPriceReaderPriceAgeCall) Return(arg0 time.Duration) *MockPriceReaderPriceAgeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPriceReaderPriceAgeCall) Do(f func(string) time.Duration) *MockPriceReaderPriceAgeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPriceReaderPriceAgeCall) DoAndReturn(f func(string) time.Duration) *MockPriceReaderPriceAgeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockFundingReader is a mock of FundingReader interface.
type MockFundingReader struct {
	ctrl     *gomock.Controller
	recorder *MockFundingReaderMockRecorder
	isgomock struct{}
}

// MockFundingReaderMockRecorder is the mock recorder for MockFundingReader.
type MockFundingReaderMockRecorder struct {
	mock *MockFundingReader
}

// NewMockFundingReader creates a new mock instance.
func NewMockFundingReader(ctrl *gomock.Controller) *MockFundingReader {
	mock := &MockFundingReader{ctrl: ctrl}
	mock.recorder = &MockFundingReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFundingReader) EXPECT() *MockFundingReaderMockRecorder {
	return m.recorder
}

// GetFunding mocks base method.
func (m *MockFundingReader) GetFunding(ctx context.Context, symbol string) (*store.FundingData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFunding", ctx, symbol)
	ret0, _ := ret[0].(*store.FundingData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFunding indicates an expected call of GetFunding.
func (mr *MockFundingReaderMockRecorder) GetFunding(ctx, symbol any) *MockFundingReaderGetFundingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFunding", reflect.TypeOf((*MockFundingReader)(nil).GetFunding), ctx, symbol)
	return &MockFundingReaderGetFundingCall{Call: call}
}

// MockFundingReaderGetFundingCall wrap *gomock.Call
type MockFundingReaderGetFundingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFundingReaderGetFundingCall) Return(arg0 *store.FundingData, arg1 error) *MockFundingReaderGetFundingCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFundingReaderGetFundingCall) Do(f func(context.Context, string) (*store.FundingData, error)) *MockFundingReaderGetFundingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFundingReaderGetFundingCall) DoAndReturn(f func(context.Context, string) (*store.FundingData, error)) *MockFundingReaderGetFundingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSettleTime mocks base method.
func (m *MockFundingReader) GetSettleTime(ctx context.Context, symbol string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettleTime", ctx, symbol)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettleTime indicates an expected call of GetSettleTime.
func (mr *MockFundingReaderMockRecorder) GetSettleTime(ctx, symbol any) *MockFundingReaderGetSettleTimeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettleTime", reflect.TypeOf((*MockFundingReader)(nil).GetSettleTime), ctx, symbol)
	return &MockFundingReaderGetSettleTimeCall{Call: call}
}

// MockFundingReaderGetSettleTimeCall wrap *gomock.Call
type MockFundingReaderGetSettleTimeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFundingReaderGetSettleTimeCall) Return(arg0 time.Time, arg1 error) *MockFundingReaderGetSettleTimeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFundingReaderGetSettleTimeCall) Do(f func(context.Context, string) (time.Time, error)) *MockFundingReaderGetSettleTimeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFundingReaderGetSettleTimeCall) DoAndReturn(f func(context.Context, string) (time.Time, error)) *MockFundingReaderGetSettleTimeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockDepthReader is a mock of DepthReader interface.
type MockDepthReader struct {
	ctrl     *gomock.Controller
	recorder *MockDepthReaderMockRecorder
	isgomock struct{}
}

// MockDepthReaderMockRecorder is the mock recorder for MockDepthReader.
type MockDepthReaderMockRecorder struct {
	mock *MockDepthReader
}

// NewMockDepthReader creates a new mock instance.
func NewMockDepthReader(ctrl *gomock.Controller) *MockDepthReader {
	mock := &MockDepthReader{ctrl: ctrl}
	mock.recorder = &MockDepthReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepthReader) EXPECT() *MockDepthReaderMockRecorder {
	return m.recorder
}

// GetDepth mocks base method.
func (m *MockDepthReader) GetDepth(ctx context.Context, symbol string) (*domain.OrderBook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepth", ctx, symbol)
	ret0, _ := ret[0].(*domain.OrderBook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepth indicates an expected call of GetDepth.
func (mr *MockDepthReaderMockRecorder) GetDepth(ctx, symbol any) *MockDepthReaderGetDepthCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepth", reflect.TypeOf((*MockDepthReader)(nil).GetDepth), ctx, symbol)
	return &MockDepthReaderGetDepthCall{Call: call}
}

// MockDepthReaderGetDepthCall wrap *gomock.Call
type MockDepthReaderGetDepthCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDepthReaderGetDepthCall) Return(arg0 *domain.OrderBook, arg1 error) *MockDepthReaderGetDepthCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDepthReaderGetDepthCall) Do(f func(context.Context, string) (*domain.OrderBook, error)) *MockDepthReaderGetDepthCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDepthReaderGetDepthCall) DoAndReturn(f func(context.Context, string) (*domain.OrderBook, error)) *MockDepthReaderGetDepthCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockKlineReadWriter is a mock of KlineReadWriter interface.
type MockKlineReadWriter struct {
	ctrl     *gomock.Controller
	recorder *MockKlineReadWriterMockRecorder
	isgomock struct{}
}

// MockKlineReadWriterMockRecorder is the mock recorder for MockKlineReadWriter.
type MockKlineReadWriterMockRecorder struct {
	mock *MockKlineReadWriter
}

// NewMockKlineReadWriter creates a new mock instance.
func NewMockKlineReadWriter(ctrl *gomock.Controller) *MockKlineReadWriter {
	mock := &MockKlineReadWriter{ctrl: ctrl}
	mock.recorder = &MockKlineReadWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKlineReadWriter) EXPECT() *MockKlineReadWriterMockRecorder {
	return m.recorder
}

// AddKline mocks base method.
func (m *MockKlineReadWriter) AddKline(symbol string, k domain.Kline) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddKline", symbol, k)
}

// AddKline indicates an expected call of AddKline.
func (mr *MockKlineReadWriterMockRecorder) AddKline(symbol, k any) *MockKlineReadWriterAddKlineCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKline", reflect.TypeOf((*MockKlineReadWriter)(nil).AddKline), symbol, k)
	return &MockKlineReadWriterAddKlineCall{Call: call}
}

// MockKlineReadWriterAddKlineCall wrap *gomock.Call
type MockKlineReadWriterAddKlineCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKlineReadWriterAddKlineCall) Return() *MockKlineReadWriterAddKlineCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKlineReadWriterAddKlineCall) Do(f func(string, domain.Kline)) *MockKlineReadWriterAddKlineCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKlineReadWriterAddKlineCall) DoAndReturn(f func(string, domain.Kline)) *MockKlineReadWriterAddKlineCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetKlines mocks base method.
func (m *MockKlineReadWriter) GetKlines(ctx context.Context, symbol string) []domain.Kline {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKlines", ctx, symbol)
	ret0, _ := ret[0].([]domain.Kline)
	return ret0
}

// GetKlines indicates an expected call of GetKlines.
func (mr *MockKlineReadWriterMockRecorder) GetKlines(ctx, symbol any) *MockKlineReadWriterGetKlinesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKlines", reflect.TypeOf((*MockKlineReadWriter)(nil).GetKlines), ctx, symbol)
	return &MockKlineReadWriterGetKlinesCall{Call: call}
}

// MockKlineReadWriterGetKlinesCall wrap *gomock.Call
type MockKlineReadWriterGetKlinesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKlineReadWriterGetKlinesCall) Return(arg0 []domain.Kline) *MockKlineReadWriterGetKlinesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKlineReadWriterGetKlinesCall) Do(f func(context.Context, string) []domain.Kline) *MockKlineReadWriterGetKlinesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKlineReadWriterGetKlinesCall) DoAndReturn(f func(context.Context, string) []domain.Kline) *MockKlineReadWriterGetKlinesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InitKlines mocks base method.
func (m *MockKlineReadWriter) InitKlines(symbol string, maxLen int, initial []domain.Kline) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitKlines", symbol, maxLen, initial)
}

// InitKlines indicates an expected call of InitKlines.
func (mr *MockKlineReadWriterMockRecorder) InitKlines(symbol, maxLen, initial any) *MockKlineReadWriterInitKlinesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitKlines", reflect.TypeOf((*MockKlineReadWriter)(nil).InitKlines), symbol, maxLen, initial)
	return &MockKlineReadWriterInitKlinesCall{Call: call}
}

// MockKlineReadWriterInitKlinesCall wrap *gomock.Call
type MockKlineReadWriterInitKlinesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKlineReadWriterInitKlinesCall) Return() *MockKlineReadWriterInitKlinesCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKlineReadWriterInitKlinesCall) Do(f func(string, int, []domain.Kline)) *MockKlineReadWriterInitKlinesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKlineReadWriterInitKlinesCall) DoAndReturn(f func(string, int, []domain.Kline)) *MockKlineReadWriterInitKlinesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
