// Code generated by MockGen. DO NOT EDIT.
// Source: crypto-bot/internal/infrastructure/watcher (interfaces: OrderNotifier)
//
// Generated by this command:
//
//	mockgen -destination mock_watcher.go -package mocks -typed crypto-bot/internal/infrastructure/watcher OrderNotifier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "crypto-bot/internal/domain"
	exchange "crypto-bot/internal/infrastructure/exchange"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderNotifier is a mock of OrderNotifier interface.
type MockOrderNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockOrderNotifierMockRecorder
	isgomock struct{}
}

// MockOrderNotifierMockRecorder is the mock recorder for MockOrderNotifier.
type MockOrderNotifierMockRecorder struct {
	mock *MockOrderNotifier
}

// NewMockOrderNotifier creates a new mock instance.
func NewMockOrderNotifier(ctrl *gomock.Controller) *MockOrderNotifier {
	mock := &MockOrderNotifier{ctrl: ctrl}
	mock.recorder = &MockOrderNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderNotifier) EXPECT() *MockOrderNotifierMockRecorder {
	return m.recorder
}

// OnPositionUpdate mocks base method.
func (m *MockOrderNotifier) OnPositionUpdate(ctx context.Context, symbol string, timeout time.Duration, callback func(exchange.PersonalPositionUpdate)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnPositionUpdate", ctx, symbol, timeout, callback)
}

// OnPositionUpdate indicates an expected call of OnPositionUpdate.
func (mr *MockOrderNotifierMockRecorder) OnPositionUpdate(ctx, symbol, timeout, callback any) *MockOrderNotifierOnPositionUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnPositionUpdate", reflect.TypeOf((*MockOrderNotifier)(nil).OnPositionUpdate), ctx, symbol, timeout, callback)
	return &MockOrderNotifierOnPositionUpdateCall{Call: call}
}

// MockOrderNotifierOnPositionUpdateCall wrap *gomock.Call
type MockOrderNotifierOnPositionUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderNotifierOnPositionUpdateCall) Return() *MockOrderNotifierOnPositionUpdateCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderNotifierOnPositionUpdateCall) Do(f func(context.Context, string, time.Duration, func(exchange.PersonalPositionUpdate))) *MockOrderNotifierOnPositionUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderNotifierOnPositionUpdateCall) DoAndReturn(f func(context.Context, string, time.Duration, func(exchange.PersonalPositionUpdate))) *MockOrderNotifierOnPositionUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// OnTradeUpdate mocks base method.
func (m *MockOrderNotifier) OnTradeUpdate(ctx context.Context, symbol string, timeout time.Duration, callback func([]domain.PublicTrade)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnTradeUpdate", ctx, symbol, timeout, callback)
}

// OnTradeUpdate indicates an expected call of OnTradeUpdate.
func (mr *MockOrderNotifierMockRecorder) OnTradeUpdate(ctx, symbol, timeout, callback any) *MockOrderNotifierOnTradeUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnTradeUpdate", reflect.TypeOf((*MockOrderNotifier)(nil).OnTradeUpdate), ctx, symbol, timeout, callback)
	return &MockOrderNotifierOnTradeUpdateCall{Call: call}
}

// MockOrderNotifierOnTradeUpdateCall wrap *gomock.Call
type MockOrderNotifierOnTradeUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderNotifierOnTradeUpdateCall) Return() *MockOrderNotifierOnTradeUpdateCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderNotifierOnTradeUpdateCall) Do(f func(context.Context, string, time.Duration, func([]domain.PublicTrade))) *MockOrderNotifierOnTradeUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderNotifierOnTradeUpdateCall) DoAndReturn(f func(context.Context, string, time.Duration, func([]domain.PublicTrade))) *MockOrderNotifierOnTradeUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
