// Code generated by MockGen. DO NOT EDIT.
// Source: crypto-bot/internal/infrastructure/ws (interfaces: Subscriber)
//
// Generated by this command:
//
//	mockgen -destination mock_ws.go -package mocks -typed crypto-bot/internal/infrastructure/ws Subscriber
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSubscriber is a mock of Subscriber interface.
type MockSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriberMockRecorder
	isgomock struct{}
}

// MockSubscriberMockRecorder is the mock recorder for MockSubscriber.
type MockSubscriberMockRecorder struct {
	mock *MockSubscriber
}

// NewMockSubscriber creates a new mock instance.
func NewMockSubscriber(ctrl *gomock.Controller) *MockSubscriber {
	mock := &MockSubscriber{ctrl: ctrl}
	mock.recorder = &MockSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriber) EXPECT() *MockSubscriberMockRecorder {
	return m.recorder
}

// SubscribePersonal mocks base method.
func (m *MockSubscriber) SubscribePersonal(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribePersonal", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribePersonal indicates an expected call of SubscribePersonal.
func (mr *MockSubscriberMockRecorder) SubscribePersonal(ctx any) *MockSubscriberSubscribePersonalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribePersonal", reflect.TypeOf((*MockSubscriber)(nil).SubscribePersonal), ctx)
	return &MockSubscriberSubscribePersonalCall{Call: call}
}

// MockSubscriberSubscribePersonalCall wrap *gomock.Call
type MockSubscriberSubscribePersonalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriberSubscribePersonalCall) Return(arg0 error) *MockSubscriberSubscribePersonalCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriberSubscribePersonalCall) Do(f func(context.Context) error) *MockSubscriberSubscribePersonalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriberSubscribePersonalCall) DoAndReturn(f func(context.Context) error) *MockSubscriberSubscribePersonalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubscribeTicker mocks base method.
func (m *MockSubscriber) SubscribeTicker(ctx context.Context, symbol string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeTicker", ctx, symbol)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeTicker indicates an expected call of SubscribeTicker.
func (mr *MockSubscriberMockRecorder) SubscribeTicker(ctx, symbol any) *MockSubscriberSubscribeTickerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeTicker", reflect.TypeOf((*MockSubscriber)(nil).SubscribeTicker), ctx, symbol)
	return &MockSubscriberSubscribeTickerCall{Call: call}
}

// MockSubscriberSubscribeTickerCall wrap *gomock.Call
type MockSubscriberSubscribeTickerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriberSubscribeTickerCall) Return(arg0 error) *MockSubscriberSubscribeTickerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriberSubscribeTickerCall) Do(f func(context.Context, string) error) *MockSubscriberSubscribeTickerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriberSubscribeTickerCall) DoAndReturn(f func(context.Context, string) error) *MockSubscriberSubscribeTickerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UnsubscribeTicker mocks base method.
func (m *MockSubscriber) UnsubscribeTicker(ctx context.Context, symbol string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeTicker", ctx, symbol)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsubscribeTicker indicates an expected call of UnsubscribeTicker.
func (mr *MockSubscriberMockRecorder) UnsubscribeTicker(ctx, symbol any) *MockSubscriberUnsubscribeTickerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeTicker", reflect.TypeOf((*MockSubscriber)(nil).UnsubscribeTicker), ctx, symbol)
	return &MockSubscriberUnsubscribeTickerCall{Call: call}
}

// MockSubscriberUnsubscribeTickerCall wrap *gomock.Call
type MockSubscriberUnsubscribeTickerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriberUnsubscribeTickerCall) Return(arg0 error) *MockSubscriberUnsubscribeTickerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriberUnsubscribeTickerCall) Do(f func(context.Context, string) error) *MockSubscriberUnsubscribeTickerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriberUnsubscribeTickerCall) DoAndReturn(f func(context.Context, string) error) *MockSubscriberUnsubscribeTickerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
