// Code generated by MockGen. DO NOT EDIT.
// Source: crypto-bot/internal/infrastructure/ws (interfaces: Subscriber)
//
// Generated by this command:
//
//	mockgen -destination mock_ws.go -package mocks -typed crypto-bot/internal/infrastructure/ws Subscriber
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSubscriber is a mock of Subscriber interface.
type MockSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriberMockRecorder
	isgomock struct{}
}

// MockSubscriberMockRecorder is the mock recorder for MockSubscriber.
type MockSubscriberMockRecorder struct {
	mock *MockSubscriber
}

// NewMockSubscriber creates a new mock instance.
func NewMockSubscriber(ctrl *gomock.Controller) *MockSubscriber {
	mock := &MockSubscriber{ctrl: ctrl}
	mock.recorder = &MockSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriber) EXPECT() *MockSubscriberMockRecorder {
	return m.recorder
}

// SubscribeDepth mocks base method.
func (m *MockSubscriber) SubscribeDepth(symbol, step string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeDepth", symbol, step)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeDepth indicates an expected call of SubscribeDepth.
func (mr *MockSubscriberMockRecorder) SubscribeDepth(symbol, step any) *MockSubscriberSubscribeDepthCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeDepth", reflect.TypeOf((*MockSubscriber)(nil).SubscribeDepth), symbol, step)
	return &MockSubscriberSubscribeDepthCall{Call: call}
}

// MockSubscriberSubscribeDepthCall wrap *gomock.Call
type MockSubscriberSubscribeDepthCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriberSubscribeDepthCall) Return(arg0 error) *MockSubscriberSubscribeDepthCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriberSubscribeDepthCall) Do(f func(string, string) error) *MockSubscriberSubscribeDepthCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriberSubscribeDepthCall) DoAndReturn(f func(string, string) error) *MockSubscriberSubscribeDepthCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubscribeKline mocks base method.
func (m *MockSubscriber) SubscribeKline(symbol string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeKline", symbol)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeKline indicates an expected call of SubscribeKline.
func (mr *MockSubscriberMockRecorder) SubscribeKline(symbol any) *MockSubscriberSubscribeKlineCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeKline", reflect.TypeOf((*MockSubscriber)(nil).SubscribeKline), symbol)
	return &MockSubscriberSubscribeKlineCall{Call: call}
}

// MockSubscriberSubscribeKlineCall wrap *gomock.Call
type MockSubscriberSubscribeKlineCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriberSubscribeKlineCall) Return(arg0 error) *MockSubscriberSubscribeKlineCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriberSubscribeKlineCall) Do(f func(string) error) *MockSubscriberSubscribeKlineCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriberSubscribeKlineCall) DoAndReturn(f func(string) error) *MockSubscriberSubscribeKlineCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubscribePersonal mocks base method.
func (m *MockSubscriber) SubscribePersonal() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribePersonal")
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribePersonal indicates an expected call of SubscribePersonal.
func (mr *MockSubscriberMockRecorder) SubscribePersonal() *MockSubscriberSubscribePersonalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribePersonal", reflect.TypeOf((*MockSubscriber)(nil).SubscribePersonal))
	return &MockSubscriberSubscribePersonalCall{Call: call}
}

// MockSubscriberSubscribePersonalCall wrap *gomock.Call
type MockSubscriberSubscribePersonalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriberSubscribePersonalCall) Return(arg0 error) *MockSubscriberSubscribePersonalCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriberSubscribePersonalCall) Do(f func() error) *MockSubscriberSubscribePersonalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriberSubscribePersonalCall) DoAndReturn(f func() error) *MockSubscriberSubscribePersonalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubscribeTicker mocks base method.
func (m *MockSubscriber) SubscribeTicker(symbol string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeTicker", symbol)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeTicker indicates an expected call of SubscribeTicker.
func (mr *MockSubscriberMockRecorder) SubscribeTicker(symbol any) *MockSubscriberSubscribeTickerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeTicker", reflect.TypeOf((*MockSubscriber)(nil).SubscribeTicker), symbol)
	return &MockSubscriberSubscribeTickerCall{Call: call}
}

// MockSubscriberSubscribeTickerCall wrap *gomock.Call
type MockSubscriberSubscribeTickerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriberSubscribeTickerCall) Return(arg0 error) *MockSubscriberSubscribeTickerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriberSubscribeTickerCall) Do(f func(string) error) *MockSubscriberSubscribeTickerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriberSubscribeTickerCall) DoAndReturn(f func(string) error) *MockSubscriberSubscribeTickerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UnsubscribeDepth mocks base method.
func (m *MockSubscriber) UnsubscribeDepth(symbol, step string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeDepth", symbol, step)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsubscribeDepth indicates an expected call of UnsubscribeDepth.
func (mr *MockSubscriberMockRecorder) UnsubscribeDepth(symbol, step any) *MockSubscriberUnsubscribeDepthCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeDepth", reflect.TypeOf((*MockSubscriber)(nil).UnsubscribeDepth), symbol, step)
	return &MockSubscriberUnsubscribeDepthCall{Call: call}
}

// MockSubscriberUnsubscribeDepthCall wrap *gomock.Call
type MockSubscriberUnsubscribeDepthCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriberUnsubscribeDepthCall) Return(arg0 error) *MockSubscriberUnsubscribeDepthCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriberUnsubscribeDepthCall) Do(f func(string, string) error) *MockSubscriberUnsubscribeDepthCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriberUnsubscribeDepthCall) DoAndReturn(f func(string, string) error) *MockSubscriberUnsubscribeDepthCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UnsubscribeKline mocks base method.
func (m *MockSubscriber) UnsubscribeKline(symbol string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeKline", symbol)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsubscribeKline indicates an expected call of UnsubscribeKline.
func (mr *MockSubscriberMockRecorder) UnsubscribeKline(symbol any) *MockSubscriberUnsubscribeKlineCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeKline", reflect.TypeOf((*MockSubscriber)(nil).UnsubscribeKline), symbol)
	return &MockSubscriberUnsubscribeKlineCall{Call: call}
}

// MockSubscriberUnsubscribeKlineCall wrap *gomock.Call
type MockSubscriberUnsubscribeKlineCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriberUnsubscribeKlineCall) Return(arg0 error) *MockSubscriberUnsubscribeKlineCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriberUnsubscribeKlineCall) Do(f func(string) error) *MockSubscriberUnsubscribeKlineCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriberUnsubscribeKlineCall) DoAndReturn(f func(string) error) *MockSubscriberUnsubscribeKlineCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UnsubscribeTicker mocks base method.
func (m *MockSubscriber) UnsubscribeTicker(symbol string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeTicker", symbol)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsubscribeTicker indicates an expected call of UnsubscribeTicker.
func (mr *MockSubscriberMockRecorder) UnsubscribeTicker(symbol any) *MockSubscriberUnsubscribeTickerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeTicker", reflect.TypeOf((*MockSubscriber)(nil).UnsubscribeTicker), symbol)
	return &MockSubscriberUnsubscribeTickerCall{Call: call}
}

// MockSubscriberUnsubscribeTickerCall wrap *gomock.Call
type MockSubscriberUnsubscribeTickerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriberUnsubscribeTickerCall) Return(arg0 error) *MockSubscriberUnsubscribeTickerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriberUnsubscribeTickerCall) Do(f func(string) error) *MockSubscriberUnsubscribeTickerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriberUnsubscribeTickerCall) DoAndReturn(f func(string) error) *MockSubscriberUnsubscribeTickerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
