// Code generated by MockGen. DO NOT EDIT.
// Source: crypto-bot/internal/infrastructure/notifier (interfaces: Notifier)
//
// Generated by this command:
//
//	mockgen -destination mock_notifier.go -package mocks -typed crypto-bot/internal/infrastructure/notifier Notifier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	notifier "crypto-bot/internal/infrastructure/notifier"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockNotifier) Send(ctx context.Context, evt notifier.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendRawMsg mocks base method.
func (m *MockNotifier) SendRawMsg(ctx context.Context, msg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRawMsg", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockNotifierMockRecorder) Send(ctx, evt any) *MockNotifierSendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockNotifier)(nil).Send), ctx, evt)
	return &MockNotifierSendCall{Call: call}
}

// MockNotifierSendCall wrap *gomock.Call
type MockNotifierSendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNotifierSendCall) Return(arg0 error) *MockNotifierSendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNotifierSendCall) Do(f func(context.Context, notifier.Event) error) *MockNotifierSendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNotifierSendCall) DoAndReturn(f func(context.Context, notifier.Event) error) *MockNotifierSendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendRawMsg indicates an expected call of SendRawMsg.
func (mr *MockNotifierMockRecorder) SendRawMsg(ctx, msg any) *MockNotifierSendRawMsgCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRawMsg", reflect.TypeOf((*MockNotifier)(nil).SendRawMsg), ctx, msg)
	return &MockNotifierSendRawMsgCall{Call: call}
}

// MockNotifierSendRawMsgCall wrap *gomock.Call
type MockNotifierSendRawMsgCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNotifierSendRawMsgCall) Return(arg0 error) *MockNotifierSendRawMsgCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNotifierSendRawMsgCall) Do(f func(context.Context, string) error) *MockNotifierSendRawMsgCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNotifierSendRawMsgCall) DoAndReturn(f func(context.Context, string) error) *MockNotifierSendRawMsgCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Start mocks base method.
func (m *MockNotifier) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockNotifierMockRecorder) Start(ctx any) *MockNotifierStartCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockNotifier)(nil).Start), ctx)
	return &MockNotifierStartCall{Call: call}
}

// MockNotifierStartCall wrap *gomock.Call
type MockNotifierStartCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNotifierStartCall) Return(arg0 error) *MockNotifierStartCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNotifierStartCall) Do(f func(context.Context) error) *MockNotifierStartCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNotifierStartCall) DoAndReturn(f func(context.Context) error) *MockNotifierStartCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stop mocks base method.
func (m *MockNotifier) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockNotifierMockRecorder) Stop(ctx any) *MockNotifierStopCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockNotifier)(nil).Stop), ctx)
	return &MockNotifierStopCall{Call: call}
}

// MockNotifierStopCall wrap *gomock.Call
type MockNotifierStopCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNotifierStopCall) Return(arg0 error) *MockNotifierStopCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNotifierStopCall) Do(f func(context.Context) error) *MockNotifierStopCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNotifierStopCall) DoAndReturn(f func(context.Context) error) *MockNotifierStopCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
