// Code generated by MockGen. DO NOT EDIT.
// Source: crypto-bot/internal/domain (interfaces: Clock)
//
// Generated by this command:
//
//	mockgen -destination mock_clock.go -package mocks -typed crypto-bot/internal/domain Clock
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// GetServerTime mocks base method.
func (m *MockClock) GetServerTime() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerTime")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetServerTime indicates an expected call of GetServerTime.
func (mr *MockClockMockRecorder) GetServerTime() *MockClockGetServerTimeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerTime", reflect.TypeOf((*MockClock)(nil).GetServerTime))
	return &MockClockGetServerTimeCall{Call: call}
}

// MockClockGetServerTimeCall wrap *gomock.Call
type MockClockGetServerTimeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClockGetServerTimeCall) Return(arg0 int64) *MockClockGetServerTimeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClockGetServerTimeCall) Do(f func() int64) *MockClockGetServerTimeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClockGetServerTimeCall) DoAndReturn(f func() int64) *MockClockGetServerTimeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsHealthy mocks base method.
func (m *MockClock) IsHealthy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHealthy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsHealthy indicates an expected call of IsHealthy.
func (mr *MockClockMockRecorder) IsHealthy() *MockClockIsHealthyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHealthy", reflect.TypeOf((*MockClock)(nil).IsHealthy))
	return &MockClockIsHealthyCall{Call: call}
}

// MockClockIsHealthyCall wrap *gomock.Call
type MockClockIsHealthyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClockIsHealthyCall) Return(arg0 bool) *MockClockIsHealthyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClockIsHealthyCall) Do(f func() bool) *MockClockIsHealthyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClockIsHealthyCall) DoAndReturn(f func() bool) *MockClockIsHealthyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LatencyMs mocks base method.
func (m *MockClock) LatencyMs() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatencyMs")
	ret0, _ := ret[0].(int64)
	return ret0
}

// LatencyMs indicates an expected call of LatencyMs.
func (mr *MockClockMockRecorder) LatencyMs() *MockClockLatencyMsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatencyMs", reflect.TypeOf((*MockClock)(nil).LatencyMs))
	return &MockClockLatencyMsCall{Call: call}
}

// MockClockLatencyMsCall wrap *gomock.Call
type MockClockLatencyMsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClockLatencyMsCall) Return(arg0 int64) *MockClockLatencyMsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClockLatencyMsCall) Do(f func() int64) *MockClockLatencyMsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClockLatencyMsCall) DoAndReturn(f func() int64) *MockClockLatencyMsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MsUntilTarget mocks base method.
func (m *MockClock) MsUntilTarget(targetServerTimeMs int64) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MsUntilTarget", targetServerTimeMs)
	ret0, _ := ret[0].(int64)
	return ret0
}

// MsUntilTarget indicates an expected call of MsUntilTarget.
func (mr *MockClockMockRecorder) MsUntilTarget(targetServerTimeMs any) *MockClockMsUntilTargetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MsUntilTarget", reflect.TypeOf((*MockClock)(nil).MsUntilTarget), targetServerTimeMs)
	return &MockClockMsUntilTargetCall{Call: call}
}

// MockClockMsUntilTargetCall wrap *gomock.Call
type MockClockMsUntilTargetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClockMsUntilTargetCall) Return(arg0 int64) *MockClockMsUntilTargetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClockMsUntilTargetCall) Do(f func(int64) int64) *MockClockMsUntilTargetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClockMsUntilTargetCall) DoAndReturn(f func(int64) int64) *MockClockMsUntilTargetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *MockClockNowCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
	return &MockClockNowCall{Call: call}
}

// MockClockNowCall wrap *gomock.Call
type MockClockNowCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClockNowCall) Return(arg0 time.Time) *MockClockNowCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClockNowCall) Do(f func() time.Time) *MockClockNowCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClockNowCall) DoAndReturn(f func() time.Time) *MockClockNowCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Offset mocks base method.
func (m *MockClock) Offset() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Offset")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Offset indicates an expected call of Offset.
func (mr *MockClockMockRecorder) Offset() *MockClockOffsetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Offset", reflect.TypeOf((*MockClock)(nil).Offset))
	return &MockClockOffsetCall{Call: call}
}

// MockClockOffsetCall wrap *gomock.Call
type MockClockOffsetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClockOffsetCall) Return(arg0 int64) *MockClockOffsetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClockOffsetCall) Do(f func() int64) *MockClockOffsetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClockOffsetCall) DoAndReturn(f func() int64) *MockClockOffsetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Sleep mocks base method.
func (m *MockClock) Sleep(ctx context.Context, d time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sleep", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sleep indicates an expected call of Sleep.
func (mr *MockClockMockRecorder) Sleep(ctx, d any) *MockClockSleepCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sleep", reflect.TypeOf((*MockClock)(nil).Sleep), ctx, d)
	return &MockClockSleepCall{Call: call}
}

// MockClockSleepCall wrap *gomock.Call
type MockClockSleepCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClockSleepCall) Return(arg0 error) *MockClockSleepCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClockSleepCall) Do(f func(context.Context, time.Duration) error) *MockClockSleepCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClockSleepCall) DoAndReturn(f func(context.Context, time.Duration) error) *MockClockSleepCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Until mocks base method.
func (m *MockClock) Until(target time.Time) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Until", target)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Until indicates an expected call of Until.
func (mr *MockClockMockRecorder) Until(target any) *MockClockUntilCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Until", reflect.TypeOf((*MockClock)(nil).Until), target)
	return &MockClockUntilCall{Call: call}
}

// MockClockUntilCall wrap *gomock.Call
type MockClockUntilCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClockUntilCall) Return(arg0 time.Duration) *MockClockUntilCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClockUntilCall) Do(f func(time.Time) time.Duration) *MockClockUntilCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClockUntilCall) DoAndReturn(f func(time.Time) time.Duration) *MockClockUntilCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
